### Add book
PUT http://localhost:3000/putbooks/64/
Content-Type: application/json

{
  "title": "Updated Title",
  "author": "Jane Doe",
  "rating": 5.0
}


### Get all books
GET http://localhost:3000/books/?title=1984
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlZXJ0aGlkYXJsaW5nIiwiaWF0IjoxNzU2NzQwNTE2fQ.pUUuqnf5dgk3zH8VA5JFd6wkokxV-imGLMGS4diOJ-g

### Get url with parameters

GET http://localhost:3000/books/?offset=2&limit=4&search_q=The&order_by=price&order=DESC

### Create new user in user table

POST http://localhost:3000/usersregister/
Content-Type: application/json

{
  "id" : 14,
  "username" : "mydarling",
  "password" : "my@1234567",
  "name" : "My Lover",
  "gender": "Female",
  "location" : "Kanimetta"
}

### Login request API

POST http://localhost:3000/login/
Content-Type: application/json

{
  "username" : "mydarling",
  "password" : "my@1234567"
}

### TO get User Profile
GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlZXJ0aGlkYXJsaW5nIiwiaWF0IjoxNzU2NzQwNTE2fQ.pUUuqnf5dgk3zH8VA5JFd6wkokxV-imGLMGS4diOJ-g


### TO get another User Profile
GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im15ZGFybGluZyIsImlhdCI6MTc1Njc0NzYyN30.ZDsjE2xX0CJfz-sDZ_sn8FTugBKJmsYgNRhdjuAiAK8